// DocuSign — send a contract, NDA or label waiver PDF for signature.
//
//   counterparty signs first (routingOrder 1), then the label's signer from
//   Settings › Label (signatory_name + signatory_email, routingOrder 2).
//   Free-form signing: no anchor tabs, because the PDFs are generated by the
//   dashboard in several layouts — each signer places their signature.
//
// Status is polled every ten minutes (lib/integrations-worker.js), refreshed
// on demand, and nudged by the optional Connect webhook. When an envelope
// completes, the combined signed PDF is stored on the artist's Documents (and
// on the contract's own files) and the contract's date_signed is stamped.
//
// OAuth 2 authorization-code grant. Access tokens last 8 hours, refresh tokens
// 30 days (they rotate). Tokens live encrypted under PAYMENT_DETAILS_KEY.
//
// Env: DOCUSIGN_INTEGRATION_KEY, DOCUSIGN_SECRET, DOCUSIGN_ENV=demo|production,
//      DOCUSIGN_DRY_RUN=1 (fixtures: no DocuSign call; envelopes complete on the second refresh).
const pool = require('../db');
const crypto = require('./payment-crypto');
const { request, basic } = require('./http-json');
const { uploadFile, loadFileBuffer } = require('./r2');

const DRY = () => process.env.DOCUSIGN_DRY_RUN === '1';
const ENV = () => (process.env.DOCUSIGN_ENV === 'production' ? 'production' : 'demo');
const AUTH_HOST = () => (ENV() === 'production' ? 'https://account.docusign.com' : 'https://account-d.docusign.com');
const SCOPES = 'signature extended';
const isConfigured = () => !!(process.env.DOCUSIGN_INTEGRATION_KEY && process.env.DOCUSIGN_SECRET);
const DOC_TYPES = { contract: 'Contract', nda: 'NDA', waiver: 'Label waiver' };

class DocuSignError extends Error {
  constructor(message, { code = 'DOCUSIGN_ERROR', status = 500 } = {}) { super(message); this.code = code; this.status = status; }
}

async function getAccount() { const { rows: [a] } = await pool.query('SELECT * FROM docusign_account WHERE id = 1'); return a || null; }

async function status() {
  const a = await getAccount();
  const { rows: [agg] } = await pool.query(`SELECT COUNT(*) FILTER (WHERE status IN ('sent','delivered'))::int AS open, COUNT(*) FILTER (WHERE status = 'completed')::int AS completed, MAX(sent_at) AS last FROM signature_envelopes`).catch(() => ({ rows: [{}] }));
  return {
    configured: isConfigured(), env: ENV(), dry_run: DRY(), connected: !!a, account_id: a?.account_id || null, account_name: a?.account_name || null,
    user_email: a?.user_email || null, status: a?.status || null, last_error: a?.last_error || null, connected_at: a?.connected_at || null,
    open: agg?.open || 0, completed: agg?.completed || 0, last_sent_at: agg?.last || null,
  };
}

function authorizeUrl({ redirectUri, state }) {
  const p = new URLSearchParams({ response_type: 'code', scope: SCOPES, client_id: process.env.DOCUSIGN_INTEGRATION_KEY, redirect_uri: redirectUri, state });
  return `${AUTH_HOST()}/oauth/auth?${p}`;
}

async function tokenRequest(form) {
  if (DRY()) return { access_token: `dry-access-${Date.now()}`, refresh_token: `dry-refresh-${Date.now()}`, expires_in: 28800 };
  const r = await request(`${AUTH_HOST()}/oauth/token`, { method: 'POST', headers: { Authorization: basic(process.env.DOCUSIGN_INTEGRATION_KEY, process.env.DOCUSIGN_SECRET) }, form });
  if (r.status >= 400 || !r.json?.access_token) {
    const msg = r.json?.error_description || r.json?.error || `HTTP ${r.status}`;
    throw new DocuSignError(`DocuSign token request failed: ${msg}`, { code: r.json?.error === 'invalid_grant' ? 'INVALID_GRANT' : 'TOKEN', status: 502 });
  }
  return r.json;
}

async function connect({ code, redirectUri, userId }) {
  if (!crypto.isConfigured()) throw new DocuSignError('Encryption key not configured; DocuSign tokens cannot be stored.', { code: 'NO_CRYPTO', status: 503 });
  const tok = await tokenRequest({ grant_type: 'authorization_code', code, redirect_uri: redirectUri });
  let info;
  if (DRY()) info = { email: 'dry@example.com', accounts: [{ account_id: 'dry-account', account_name: 'Dry Run Records', base_uri: 'https://demo.docusign.net', is_default: true }] };
  else {
    const r = await request(`${AUTH_HOST()}/oauth/userinfo`, { headers: { Authorization: `Bearer ${tok.access_token}` } });
    if (r.status >= 400 || !r.json?.accounts?.length) throw new DocuSignError('DocuSign did not return an account for this user.', { code: 'NO_ACCOUNT', status: 502 });
    info = r.json;
  }
  const acct = info.accounts.find((a) => a.is_default) || info.accounts[0];
  await pool.query(`INSERT INTO docusign_account (id, account_id, account_name, base_uri, env, user_email, refresh_token_enc, access_token_enc, access_expires_at, status, last_error, connected_by, connected_at, updated_at)
     VALUES (1, $1, $2, $3, $4, $5, $6, $7, $8, 'active', NULL, $9, NOW(), NOW())
     ON CONFLICT (id) DO UPDATE SET account_id = EXCLUDED.account_id, account_name = EXCLUDED.account_name, base_uri = EXCLUDED.base_uri, env = EXCLUDED.env, user_email = EXCLUDED.user_email,
       refresh_token_enc = EXCLUDED.refresh_token_enc, access_token_enc = EXCLUDED.access_token_enc, access_expires_at = EXCLUDED.access_expires_at, status = 'active', last_error = NULL, connected_by = EXCLUDED.connected_by, connected_at = NOW(), updated_at = NOW()`,
    [acct.account_id, acct.account_name || null, acct.base_uri, ENV(), info.email || null, tok.refresh_token ? crypto.encrypt(tok.refresh_token) : null, crypto.encrypt(tok.access_token),
      new Date(Date.now() + (Number(tok.expires_in || 28800) - 120) * 1000), userId || null]);
  return { account_id: acct.account_id, account_name: acct.account_name, user_email: info.email };
}

async function disconnect() { const { rowCount } = await pool.query('DELETE FROM docusign_account WHERE id = 1'); return rowCount === 1; }

async function accessToken() {
  const a = await getAccount();
  if (!a) throw new DocuSignError('DocuSign is not connected. Connect it under Settings › Integrations.', { code: 'NOT_CONNECTED', status: 409 });
  if (a.status === 'needs_reconnect') throw new DocuSignError('DocuSign needs to be reconnected.', { code: 'NEEDS_RECONNECT', status: 409 });
  if (a.access_token_enc && a.access_expires_at && new Date(a.access_expires_at) > new Date()) { const t = crypto.decrypt(a.access_token_enc); if (t) return { token: t, a }; }
  const rt = crypto.decrypt(a.refresh_token_enc || '');
  if (!rt) throw new DocuSignError('DocuSign refresh token is missing; reconnect.', { code: 'NEEDS_RECONNECT', status: 409 });
  try {
    const tok = await tokenRequest({ grant_type: 'refresh_token', refresh_token: rt });
    await pool.query(`UPDATE docusign_account SET access_token_enc = $1, access_expires_at = $2, refresh_token_enc = COALESCE($3, refresh_token_enc), status = 'active', last_error = NULL, updated_at = NOW() WHERE id = 1`,
      [crypto.encrypt(tok.access_token), new Date(Date.now() + (Number(tok.expires_in || 28800) - 120) * 1000), tok.refresh_token ? crypto.encrypt(tok.refresh_token) : null]);
    return { token: tok.access_token, a };
  } catch (e) {
    if (e.code === 'INVALID_GRANT') await pool.query(`UPDATE docusign_account SET status = 'needs_reconnect', last_error = $1, updated_at = NOW() WHERE id = 1`, [e.message]);
    throw e;
  }
}

// ─── the API (with a tiny dry-run DocuSign) ───────────────────────────────
const dry = { seq: 0, envelopes: new Map() };
function dryApi(method, path, body, raw) {
  if (method === 'POST' && /\/envelopes$/.test(path)) {
    const id = `dry-${++dry.seq}-${Date.now()}`;
    dry.envelopes.set(id, { checks: 0, pdf: Buffer.from(body.documents[0].documentBase64, 'base64'), voided: false });
    return { envelopeId: id, status: 'sent' };
  }
  const m = /\/envelopes\/([^/]+)(\/.*)?$/.exec(path); const env = m && dry.envelopes.get(m[1]);
  if (!env) return raw ? Buffer.alloc(0) : {};
  if (method === 'PUT') { env.voided = true; return {}; }
  if (m[2] === '/documents/combined') return env.pdf;
  if (m[2] === '/recipients') return { signers: [{ recipientId: '1', status: env.checks >= 1 ? 'completed' : 'sent' }, { recipientId: '2', status: env.checks >= 2 ? 'completed' : 'created' }] };
  env.checks += 1;
  return { envelopeId: m[1], status: env.voided ? 'voided' : env.checks >= 2 ? 'completed' : 'delivered', completedDateTime: env.checks >= 2 ? new Date().toISOString() : undefined };
}

async function api(method, path, body, { raw = false } = {}) {
  if (DRY()) return dryApi(method, path, body, raw);
  const { token, a } = await accessToken();
  const url = `${a.base_uri}/restapi/v2.1/accounts/${encodeURIComponent(a.account_id)}${path}`;
  let r = await request(url, { method, headers: { Authorization: `Bearer ${token}`, ...(raw ? { Accept: 'application/pdf' } : {}) }, body, raw, timeoutMs: 60000 });
  if (r.status === 401) { await pool.query('UPDATE docusign_account SET access_expires_at = NULL WHERE id = 1'); const again = await accessToken(); r = await request(url, { method, headers: { Authorization: `Bearer ${again.token}`, ...(raw ? { Accept: 'application/pdf' } : {}) }, body, raw, timeoutMs: 60000 }); }
  if (r.status >= 400) {
    const msg = r.json?.message || r.json?.errorCode || (r.text || '').slice(0, 300) || `HTTP ${r.status}`;
    throw new DocuSignError(`DocuSign: ${msg}`, { code: r.json?.errorCode ? `DS_${r.json.errorCode}` : 'DS_HTTP', status: 502 });
  }
  return raw ? r.buffer : r.json;
}

// ─── documents ────────────────────────────────────────────────────────────
async function fileBytes(fileId) {
  const { rows: [f] } = await pool.query('SELECT id, r2_key, file_data, mime_type, original_name FROM entity_files WHERE id = $1', [fileId]);
  if (!f) return null;
  const buffer = await loadFileBuffer(f.r2_key, f.file_data);
  return buffer ? { buffer, name: f.original_name || `document-${f.id}.pdf`, id: f.id } : null;
}

// Store bytes as an entity_files row (R2 when configured, else the legacy column).
async function storeFile({ entityType, entityId, buffer, filename, label, userId }) {
  const safe = String(filename || 'document.pdf').replace(/[^a-zA-Z0-9._-]/g, '_').slice(0, 120);
  const stored = `${Date.now()}-${safe}`;
  let r2Key = null, fileData = null;
  try { r2Key = await uploadFile(`entity_files/${entityType}/${entityId}/${stored}`, buffer, 'application/pdf'); } catch { r2Key = null; }
  if (!r2Key) fileData = buffer.toString('base64');
  const { rows: [row] } = await pool.query(`INSERT INTO entity_files (entity_type, entity_id, filename, original_name, file_size, uploaded_by, uploaded_at, label, file_data, mime_type, r2_key)
    VALUES ($1, $2, $3, $4, $5, $6, NOW(), $7, $8, 'application/pdf', $9) RETURNING id, filename`, [entityType, entityId, stored, safe, buffer.length, userId || null, label, fileData, r2Key]);
  return row;
}

// What the document is, who the counterparty is, and where its PDF lives.
async function describe(docType, docId, uploaded) {
  if (docType === 'contract') {
    const { rows: [c] } = await pool.query(`SELECT c.*, a.name AS artist_name, a.email AS artist_email FROM contracts c LEFT JOIN artists a ON a.id = c.artist_id WHERE c.id = $1`, [docId]);
    if (!c) throw new DocuSignError('Contract not found', { code: 'NOT_FOUND', status: 404 });
    const { rows: [f] } = await pool.query(`SELECT id FROM entity_files WHERE entity_type = 'contract' AND entity_id = $1 AND (mime_type = 'application/pdf' OR original_name ILIKE '%.pdf') ORDER BY uploaded_at DESC LIMIT 1`, [docId]);
    const file = uploaded || (f ? await fileBytes(f.id) : null);
    if (!file) throw new DocuSignError('This contract has no PDF on file. Upload the contract PDF first, then send it.', { code: 'NO_PDF', status: 400 });
    return { title: `${c.type || 'Contract'} — ${c.artist_name || 'artist'}`, artistId: c.artist_id, defaultSigner: { name: c.artist_name, email: c.artist_email }, file };
  }
  if (docType === 'nda') {
    const { rows: [n] } = await pool.query('SELECT * FROM boom_ndas WHERE id = $1', [docId]);
    if (!n) throw new DocuSignError('NDA not found', { code: 'NOT_FOUND', status: 404 });
    if (!uploaded) throw new DocuSignError('The NDA PDF is rendered in the browser; the page sends it along.', { code: 'NO_PDF', status: 400 });
    const { rows: [a] } = await pool.query('SELECT id FROM artists WHERE LOWER(name) = LOWER($1) LIMIT 1', [n.recipient_name || '']).catch(() => ({ rows: [] }));
    return { title: `NDA — ${n.recipient_name || 'recipient'}`, artistId: a?.id || null, defaultSigner: { name: n.recipient_name, email: n.recipient_email }, file: uploaded };
  }
  if (docType === 'waiver') {
    const { rows: [w] } = await pool.query('SELECT * FROM boom_label_waivers WHERE id = $1', [docId]);
    if (!w) throw new DocuSignError('Waiver not found', { code: 'NOT_FOUND', status: 404 });
    const file = uploaded || (w.file_id ? await fileBytes(w.file_id) : null);
    if (!file) throw new DocuSignError('This waiver has no PDF stored yet.', { code: 'NO_PDF', status: 400 });
    return { title: `Label waiver — ${w.song_title || w.other_label_artist || 'song'}`, artistId: w.artist_id || null, defaultSigner: { name: w.other_label_artist || w.releasing_label, email: w.contact_email }, file };
  }
  throw new DocuSignError('Unknown document type', { code: 'BAD_TYPE', status: 400 });
}

async function labelSigner() {
  const { rows: [l] } = await pool.query('SELECT signatory_name, signatory_email, display_name, legal_name FROM label_settings WHERE id = 1').catch(() => ({ rows: [] }));
  return { name: l?.signatory_name || l?.display_name || l?.legal_name || 'Market Street', email: l?.signatory_email || null };
}

// ─── send ─────────────────────────────────────────────────────────────────
async function send({ docType, docId, signerName, signerEmail, message, uploaded, userId }) {
  if (!DOC_TYPES[docType]) throw new DocuSignError('Unknown document type', { code: 'BAD_TYPE', status: 400 });
  if (!(await getAccount())) throw new DocuSignError('DocuSign is not connected. Connect it under Settings › Integrations.', { code: 'NOT_CONNECTED', status: 409 });
  const d = await describe(docType, Number(docId), uploaded);
  const name = String(signerName || d.defaultSigner.name || '').trim();
  const email = String(signerEmail || d.defaultSigner.email || '').trim().toLowerCase();
  if (!name || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) throw new DocuSignError('The signer needs a name and a valid email.', { code: 'BAD_SIGNER', status: 400 });
  const label = await labelSigner();
  if (!label.email) throw new DocuSignError('Set the label signer’s email under Settings › Label (Signatory) before sending for signature.', { code: 'NO_LABEL_SIGNER', status: 400 });
  if (label.email.toLowerCase() === email) throw new DocuSignError('The counterparty and the label signer are the same address.', { code: 'BAD_SIGNER', status: 400 });
  // The source PDF is kept as a file row so the envelope is reproducible.
  const src = d.file.id ? { id: d.file.id } : await storeFile({ entityType: docType, entityId: Number(docId), buffer: d.file.buffer, filename: d.file.name, label: `${DOC_TYPES[docType]} (sent for signature)`, userId });
  const body = {
    emailSubject: `Please sign: ${d.title}`.slice(0, 100), emailBlurb: (message || `${label.name} has sent you ${DOC_TYPES[docType].toLowerCase()} to sign.`).slice(0, 10000),
    documents: [{ documentBase64: d.file.buffer.toString('base64'), name: String(d.file.name || 'document.pdf').replace(/\.pdf$/i, '') + '.pdf', fileExtension: 'pdf', documentId: '1' }],
    recipients: { signers: [
      { email, name, recipientId: '1', routingOrder: '1' },
      { email: label.email, name: label.name, recipientId: '2', routingOrder: '2' },
    ] },
    status: 'sent',
  };
  const out = await api('POST', '/envelopes', body);
  if (!out?.envelopeId) throw new DocuSignError('DocuSign did not return an envelope id.');
  const { rows: [row] } = await pool.query(`INSERT INTO signature_envelopes (envelope_id, doc_type, doc_id, artist_id, source_file_id, title, signer_name, signer_email, countersigner_name, countersigner_email, status, signer_status, countersigner_status, sent_by, message)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'sent', 'sent', 'created', $11, $12) RETURNING *`,
    [out.envelopeId, docType, Number(docId), d.artistId, src.id, d.title, name, email, label.name, label.email, userId || null, message || null]);
  return row;
}

// ─── status ───────────────────────────────────────────────────────────────
const TERMINAL = new Set(['completed', 'declined', 'voided']);

async function refreshEnvelope(row) {
  if (!row || !row.envelope_id) return row;
  if (TERMINAL.has(row.status)) return row;
  try {
    const env = await api('GET', `/envelopes/${encodeURIComponent(row.envelope_id)}`);
    const rec = await api('GET', `/envelopes/${encodeURIComponent(row.envelope_id)}/recipients`).catch(() => null);
    const signers = rec?.signers || [];
    const s1 = signers.find((s) => String(s.recipientId) === '1')?.status || row.signer_status;
    const s2 = signers.find((s) => String(s.recipientId) === '2')?.status || row.countersigner_status;
    const status = String(env?.status || row.status).toLowerCase();
    let signedFileId = row.signed_file_id;
    if (status === 'completed' && !signedFileId) {
      const pdf = await api('GET', `/envelopes/${encodeURIComponent(row.envelope_id)}/documents/combined`, undefined, { raw: true });
      if (pdf && pdf.length) {
        const base = `${row.title.replace(/[^a-zA-Z0-9 _-]/g, '').trim() || DOC_TYPES[row.doc_type]} (signed).pdf`;
        if (row.artist_id) signedFileId = (await storeFile({ entityType: 'artist', entityId: row.artist_id, buffer: pdf, filename: base, label: `Signed ${DOC_TYPES[row.doc_type].toLowerCase()}`, userId: row.sent_by })).id;
        if (row.doc_type === 'contract') {
          const f = await storeFile({ entityType: 'contract', entityId: row.doc_id, buffer: pdf, filename: base, label: 'Signed contract', userId: row.sent_by });
          if (!signedFileId) signedFileId = f.id;
          await pool.query(`UPDATE contracts SET date_signed = COALESCE(date_signed, CURRENT_DATE), file_path = COALESCE(file_path, $2) WHERE id = $1`, [row.doc_id, `/uploads/${f.filename}`]).catch(() => {});
        }
        if (row.doc_type === 'waiver' && !signedFileId) signedFileId = (await storeFile({ entityType: 'waiver', entityId: row.doc_id, buffer: pdf, filename: base, label: 'Signed label waiver', userId: row.sent_by })).id;
        if (row.doc_type === 'nda' && !signedFileId) signedFileId = (await storeFile({ entityType: 'nda', entityId: row.doc_id, buffer: pdf, filename: base, label: 'Signed NDA', userId: row.sent_by })).id;
      }
    }
    const { rows: [updated] } = await pool.query(`UPDATE signature_envelopes SET status = $2, signer_status = $3, countersigner_status = $4, completed_at = CASE WHEN $2 = 'completed' THEN COALESCE(completed_at, NOW()) ELSE completed_at END,
      signed_file_id = COALESCE($5, signed_file_id), last_checked_at = NOW(), last_error = NULL WHERE id = $1 RETURNING *`, [row.id, status, s1, s2, signedFileId || null]);
    return updated;
  } catch (e) {
    await pool.query('UPDATE signature_envelopes SET last_checked_at = NOW(), last_error = $2 WHERE id = $1', [row.id, String(e.message).slice(0, 500)]).catch(() => {});
    if (e.code === 'NOT_CONNECTED' || e.code === 'NEEDS_RECONNECT') throw e;
    return { ...row, last_error: e.message };
  }
}

async function pollEnvelopes({ limit = 100 } = {}) {
  if (!(await getAccount())) return { checked: 0 };
  const { rows } = await pool.query(`SELECT * FROM signature_envelopes WHERE status NOT IN ('completed','declined','voided') AND envelope_id IS NOT NULL ORDER BY COALESCE(last_checked_at, sent_at) ASC LIMIT $1`, [limit]);
  let checked = 0, completed = 0;
  for (const r of rows) { const u = await refreshEnvelope(r); checked += 1; if (u.status === 'completed') completed += 1; }
  return { checked, completed };
}

async function voidEnvelope(row, reason) {
  if (TERMINAL.has(row.status)) throw new DocuSignError('This envelope is already closed.', { code: 'CLOSED', status: 400 });
  await api('PUT', `/envelopes/${encodeURIComponent(row.envelope_id)}`, { status: 'voided', voidedReason: String(reason || 'Voided from the dashboard').slice(0, 200) });
  const { rows: [u] } = await pool.query(`UPDATE signature_envelopes SET status = 'voided', last_checked_at = NOW() WHERE id = $1 RETURNING *`, [row.id]);
  return u;
}

module.exports = { isConfigured, status, authorizeUrl, connect, disconnect, getAccount, send, refreshEnvelope, pollEnvelopes, voidEnvelope, labelSigner, DOC_TYPES, DocuSignError, ENV, DRY };
